#!/bin/bash

echo "🚗----- starting -----"
read -t 30 -p "contents of this submission:" content
echo "🚗----- commit   -----"
git add .
git commit -m "$content"
git pull
git push
echo "🚗----- building -----"
jekyll build
echo "🚗----- start pushing -----"
cd _site
touch CNAME
echo "imooc.me" > CNAME
git add .
git commit -m "$content"
git push -f
echo "🚗----- deploy success -----"